version: "3.9"

services:
  web:
    build: .
    command: gunicorn bloc_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/bloc
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-%atz-@4f2-6041$$n=u-0%h6geg*e0=n&fts$$v(zg_u&@_$$so)1"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSIONS_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: