# Generated by Django 4.0.5 on 2022-07-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pricing_plan',
            field=models.CharField(blank=True, choices=[('S', 'startup'), ('E', 'enterprise')], max_length=10),
        ),
    ]
